### **Performing matrix multiplication and finding eigen vectors and eigen values using TensorFlow**

In [1]:
# importing numpy library
import numpy as np

# create numpy 2d-array
m = np.array([[1, 2],
			[2, 3]])

print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Printing the Eigen values of the given square array:\n",w)
print()
# printing eigen vectors
print("Printing Right Eigen Vectors of the given square array:\n",v)



Printing the Original square array:
 [[1 2]
 [2 3]]

***************************************

Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]

Printing Right Eigen Vectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [2]:
# importing numpy library
import numpy as np

# create numpy 2d-array
m = np.array([[1, 2, 3],
			[2, 3, 4],
			[4, 5, 6]])

print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()

# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Printing the Eigen values of the given square array:\n",w)
print()
# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",v)

Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

***************************************

Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]

Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [3]:
import tensorflow as tf

In [4]:
# Let's see how we can compute the eigen vectors and values from a matrix

e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

Matrix A: 
[[4.107431  9.800611 ]
 [3.1747313 3.01891  ]]




In [7]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[-0.6446045   0.76451623]
 [ 0.76451623  0.6446045 ]] 

Eigen Values: 
[0.34212434 6.7842164 ]



In [ ]:
# Let's see how we can compute the eigen vectors and values from a matrix

e_matrix_A = tf.random.uniform([3, 3], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

In [9]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[-4.2997709e-01 -7.1157193e-01  5.5568457e-01]
 [ 7.9064959e-01  3.7567643e-04  6.1226922e-01]
 [-4.3588227e-01  7.0261347e-01  5.6244242e-01]] 

Eigen Values: 
[-4.846877  -1.3086398 18.276552 ]

